[workspace]
members = [
    "backend",
    "frontend",
    "shared_core",
]
resolver = "2"

[workspace.dependencies]
fluent = { version = "0.16" }
rust_decimal = { version = "1.42", features = ["macros", "serde-float"] }
rust_decimal_macros = "1.40"
sqlx = { version = "0.7", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "uuid",
    "chrono",
    "macros",
    "rust_decimal"
] }
uuid = { version = "1", features = ["v4", "serde"] }
