/*
 * Copyright (c) 2026.
 *
 * This file is part of KelpieBooks. For terms of use, please see the file
 * called LICENSE at the top level of the KelpieBooks source tree
 * (online at: https://github.com/shartrec/kelpiebooks/LICENSE ).
 */

use rocket_db_pools::Connection;
use shared_core::inventory::{
    dtos::inventory::BulkLocationGenerateRequest,
    models::warehouse::WarehouseLocation,
};
use uuid::Uuid;

use crate::{
    inventory::db::location as location_db,
    util::ApiError,
    DbKelpie,
};

pub async fn get_locations_for_warehouse(
    pool: &mut Connection<DbKelpie>,
    warehouse_id: Uuid,
    org_id: Uuid,
) -> Result<Vec<WarehouseLocation>, sqlx::Error> {
    location_db::all_by_warehouse(pool, warehouse_id, org_id).await
}

pub async fn get_location(
    pool: &mut Connection<DbKelpie>,
    id: Uuid,
    org_id: Uuid,
) -> Result<Option<WarehouseLocation>, sqlx::Error> {
    crate::inventory::db::location::get_location(pool, id, org_id).await
}

pub async fn create_location(
    pool: &mut Connection<DbKelpie>,
    org_id: Uuid,
    loc: &WarehouseLocation,
) -> Result<WarehouseLocation, sqlx::Error> {
    crate::inventory::db::location::create_location(pool, org_id, loc).await
}

pub async fn update_location(
    pool: &mut Connection<DbKelpie>,
    id: Uuid,
    org_id: Uuid,
    loc: &WarehouseLocation,
) -> Result<WarehouseLocation, sqlx::Error> {
    crate::inventory::db::location::update_location(pool, id, org_id, loc).await
}

pub async fn generate_locations(
    pool: &mut Connection<DbKelpie>,
    warehouse_id: Uuid,
    org_id: Uuid,
    req: &BulkLocationGenerateRequest,
) -> Result<Vec<WarehouseLocation>, ApiError> {
    let mut generated = Vec::new();

    // 1. Resolve Range Dimensions (falling back to single item 1/A if none specified)
    let aisles: Vec<String> = match &req.aisles {
        Some(range) => (range.start..=range.end).map(|v| v.to_string()).collect(),
        None => vec!["1".to_string()],
    };

    let bins: Vec<String> = match &req.bins {
        Some(range) => (range.start..=range.end).map(|v| v.to_string()).collect(),
        None => vec!["1".to_string()],
    };

    let shelves: Vec<String> = match &req.shelves {
        Some(range) => {
            let start_char = range.start.chars().next().unwrap_or('A');
            let end_char = range.end.chars().next().unwrap_or('A');
            (start_char..=end_char).map(|c| c.to_string()).collect()
        }
        None => vec!["A".to_string()],
    };

    // 2. Cartesian Matrix Expansion Loop
    for aisle in &aisles {
        for shelf in &shelves {
            for bin in &bins {
                // Parse naming pattern: {zone}-{aisle}-{shelf}-{bin}
                let display_label = req
                    .naming_format
                    .replace("{zone}", &req.zone)
                    .replace("{aisle}", aisle)
                    .replace("{shelf}", shelf)
                    .replace("{bin}", bin);

                generated.push(WarehouseLocation {
                    id: Uuid::new_v4(),
                    warehouse_id,
                    organization_id: org_id,
                    zone: Some(req.zone.clone()),
                    aisle: Some(aisle.clone()),
                    shelf: Some(shelf.clone()),
                    bin: Some(bin.clone()),
                    display_label,
                    is_picking_location: req.is_picking_location,
                    created_at: None,
                });
            }
        }
    }

    if generated.is_empty() {
        return Err(ApiError::BadRequest(
            "No locations were generated by the provided range parameters.".to_string(),
        ));
    }

    // 3. Persist batch to DB
    location_db::bulk_insert(pool, &generated).await?;

    Ok(generated)
}
